// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzfjxcvsrdgpmblyjejm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Zmp4Y3ZzcmRncG1ibHlqZWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDMwMzIsImV4cCI6MjA2OTExOTAzMn0.gy12MclZTv2rnD3U3cDybkmC2-gLQtGwPE7TeScFpKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});